### ISSUE TITLE
Windows love2d build issue (HarfBuzz)

### ISSUE THREAD

**Issue by quentin452** [love2d/megasource#13]
i use Visual Studio 2022

i tried building using visual studio : 
impossible to include hb.h
![image](https://github.com/love2d/megasource/assets/42176772/ad7370bb-8a13-48b1-a64a-42c1fdefb4e8)

i tried building using these commands : 

$ (cloned megasource with github desktop)
$ cd C:\Users\iamacatfr\Desktop\github-intellidea\megasourcez
$ (cloned love with github desktop and copy and pasted love in megasource libs)
$ cmake -G "Visual Studio 17 2022" -A x64 -S. -Bbuild
$ cmake --build build --target love/love --config Release

and impossible to include hb.h
![image](https://github.com/love2d/megasource/assets/42176772/238dba1f-3457-4d58-8103-7d56885b6e9b)

**Comment by slime73** [comment]
It looks like you're trying to build love 12 (love 11 doesn't use Harfbuzz). The `main` branch of the main love repository contains love 12 now, and the `11.x` branches of that repository and megasource contain love 11 if you actually want that.

If you do intend to build love 12, you'll need to make sure you're using the latest `main` branch of megasource as well, and if you have old generated CMake build files from before love 12 was merged into `main` you may need to clean those up.

**Comment by quentin452** [comment]
i need to build love 11  ,just I didn't notice that I was trying to build the wrong one

building 11.x is work
