### ISSUE TITLE
Update libraries?

### ISSUE THREAD

**Issue by ryandesign** [love2d/megasource#20]
Should the libraries be updated to latest versions?

https://github.com/love2d/megasource/blob/cffd50926d5e1b630315c588b44307f1190564a5/CMakeLists.txt#L219-L229

Current versions are zlib 1.3.1, luajit does not use version numbers but a newer commit exists, libogg 1.3.5, libvorbis 1.3.7, libsdl2 2.30.3, libmodplug 0.8.9.0.

**Comment by ryandesign** [comment]
And no `MEGA_HARFBUZZ_VER` variable exists but you have harfbuzz 5.3.1, current is 8.4.0.

**Comment by slime73** [comment]
New versions of libraries are always going to exist. We generally do important updates before a major release if there's no pressing reason to update earlier.
