### ISSUE TITLE
How to compile win64 ？

### ISSUE THREAD

**Issue by dumk1217** [love2d/megasource#9]
cmake -G "Visual Studio 16 2019" -A Win64 -H. -Bbuild
fail

**Comment by MikuAuahDark** [comment]
What are the error messages? I've recently succesfully compiled it using Visual Studio 2022.

**Comment by dumk1217** [comment]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.8
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft Windows [版本 10.0.17763.1577]
(c) 2018 Microsoft Corporation。保留所有权利。
:\Users\admin\Desktop\megasource>cmake -G "Visual Studio 16 2019" -A Win64 -H. -Bbuild64
CMake Error: The current CMakeCache.txt directory C:/Users/admin/Desktop/megasource/build64/CMakeCache.txt is different than the directory c:/Users/admin/Desktop/megasource12.0/build64 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "C:/Users/admin/Desktop/megasource/CMakeLists.txt" does not match the source "C:/Users/admin/Desktop/megasource12.0/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

C:\Users\admin\Desktop\megasource>cmake -G "Visual Studio 16 2019" -A Win64 -H. -Bbuild64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:10 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2021/12/28 11:47:29。
    节点 1 上的项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”( 默认目标)。
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
    已完成生成项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.45


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/admin/Desktop/megasource/build64/CMakeFiles/CMakeOutput.log".


CMakeOutput.log
The system is: Windows - 10.0.17763 - AMD64

**Comment by dumk1217** [comment]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.8
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft Windows [版本 10.0.17763.1577]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\admin\Desktop>cd megasource

C:\Users\admin\Desktop\megasource>cmake -G "Visual Studio 16 2019" -A Win64 -H. -Bbuild64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:10 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2021/12/28 11:50:46。
    节点 1 上的项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”( 默认目标)。
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
    已完成生成项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckForInvalidConfigurationAndPlatform 目标) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.51


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/admin/Desktop/megasource/build64/CMakeFiles/CMakeOutput.log".

CMakeOutput.log
The system is: Windows - 10.0.17763 - AMD64

**Comment by MikuAuahDark** [comment]
Normally you don't need to run Visual Studio command prompt. CMake will handle everything else.

**Comment by dumk1217** [comment]
Same result



C:\Users\admin\Desktop\megasource>cmake -G "Visual Studio 16 2019" -A Win64 -H. -Bbuild64
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:10 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2021/12/28 11:57:08。
    节点 1 上的项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”( 默认目标)。
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='Win64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj]
    已完成生成项目“C:\Users\admin\Desktop\megasource\build64\CMakeFiles\3.20.21032501-MSVC_2\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

**Comment by MikuAuahDark** [comment]
Ah, `Win64` architecture doesn't exist. It's either `x64` (default) or `ARM64` (12.0 only, not officially supported)
